# Generated by Django 4.2.11 on 2024-04-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="update_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
