# Generated by Django 4.2.11 on 2024-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="challenge",
            field=models.FloatField(default=3.0),
        ),
    ]
